### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by LandiMi2** [bioinformatics-hub-ke/trial2_website.github.io#3]
Hello @tobyhodges, still about index.md. I find the text aligned center making the bullet points far away from the text (points) for example membership page. How do I fix this to make the text in benefit aligned to the left?

**Comment by tobyhodges** [comment]
it seems that the text style of a section can be set with the `text_style` parameter in the section file front matter (YAML header). (for example, see line 4 of `includes/call-to-action.html`.) Values for `text_style` should match up with class names in `assets/creative.css`*. Try adding `text_style: text_left` to the header info for the "Membership" section and see if that makes the page look different...

\* that's a _long_ CSS file, but a <kbd>Ctrl</kbd> + <kbd>F</kbd> search for 'text_' should find what you're looking for.

**Comment by LandiMi2** [comment]
Try adding text_style: text_left to the header info for the "Membership" section and see if that makes the page look different...

This worked!!! Thanks, @tobyhodges
